version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - imagemagick
  tools:
    python: "3.11"

formats:
  - epub
  - pdf

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py